### ISSUE TITLE
Asteroid patches

### ISSUE THREAD

**Issue by nemysis** [chazomaticus/asteroid#2]
Hello Charles Lindsay

Please add these patches

```\n
cat  asteroid-1.2.1-CMakeLists.txt.patch
--- CMakeLists.txt.orig 2014-10-15 02:25:30.000000000 +0200
+++ CMakeLists.txt      2014-10-20 13:03:19.908402756 +0200
@@ -31,7 +31,7 @@
 endif(SDL_FOUND AND SDLMIXER_FOUND)
 
 # Config header
-set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/asteroid")
+SET(CMAKE_INSTALL_PREFIX "")
 configure_file("${PROJECT_SOURCE_DIR}/src/config.h.in" "${PROJECT_BINARY_DIR}/include/config.h")
 include_directories("${PROJECT_BINARY_DIR}/include")
```

```\n
# fix include and path
sed -i -e 's|${OPENGL_LIBRARIES}|-lm ${OPENGL_LIBRARIES}|' \
    -i -e 's|CMAKE_INSTALL_PREFIX ""|CMAKE_INSTALL_PREFIX "/usr"|' \
     CMakeLists.txt
```

**Comment by chazomaticus** [comment]
Hi @nemysis, thanks for all your help!

I think your second patch, the sed command, isn't necessary anymore (and the /usr part could be folded into the first patch).

Can you explain what the first patch is accomplishing?  I think I set Asteroid_BUILD_RES_INSTALL_PATH that way for a reason.

**Comment by nemysis** [comment]
Hi @chazomaticus

When i use in Patch


```\n
-set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/asteroid")
+set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/usr")
```
I get

```\n
[  109s] RPM build errors:
[  109s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/bin/asteroid
[  109s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/applications/asteroid.desktop
[  109s]     Directory not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/icons/hicolor
[  109s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/asteroid
```

And in spec

```\n
# fix include and path
sed -i -e 's|${OPENGL_LIBRARIES}|-lm ${OPENGL_LIBRARIES}|' \
     CMakeLists.txt
```
because all is installed in

```
/usr/local
```

what is wrong.

**Comment by chazomaticus** [comment]
And what does it say now without any patches?

I'm not keen on committing a patch that puts *anything* in /usr directly, since that's what you *don't* want when you're building from source.  It's the package maintainer's responsibility to install it under /usr in the package build.

**Comment by nemysis** [comment]
Not help also this

```\n
cat asteroid-CMakeLists.txt.patch

-set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/asteroid")
+set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/asteroid")
 configure_file("${PROJECT_SOURCE_DIR}/src/config.h.in" "${PROJECT_BINARY_DIR}/include/config.h")
```

And without  patch get same

```\n
[  101s] RPM build errors:
[  101s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/bin/asteroid
[  101s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/applications/asteroid.desktop
[  101s]     Directory not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/icons/hicolor
[  101s]     File not found: /home/abuild/rpmbuild/BUILDROOT/asteroid-1.2.1-0.x86_64/usr/share/asteroid
```

**Comment by nemysis** [comment]
Same get with

```\n
-set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/asteroid")
+set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}")
```

Please add patch

```\n
 # Config header
-set(Asteroid_BUILD_RES_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/asteroid")
+SET(CMAKE_INSTALL_PREFIX "")
 configure_file("${PROJECT_SOURCE_DIR}/src/config.h.in" "${PROJECT_BINARY_DIR}/include/config.h")
 include_directories("${PROJECT_BINARY_DIR}/include")
```

**Comment by chazomaticus** [comment]
@nemysis, I can't exactly patch in the source around problems with building RPMs.  Just building the source seems to work fine, and I haven't heard from anybody otherwise.

I'm not keen on submitting a patch that eliminates the value for a definition in `config.h.in`.  I'm also not keen on a patch that clears the install prefix across the board.

How does it behave if you build from clean source, changing your cmake command line to include `-DCMAKE_INSTALL_PREFIX=/usr`?

**Comment by nemysis** [comment]
Hi @chazomaticus, thanks for the tip i use now

```\n
%build
# Not works build with %%cmake
cmake . -DCMAKE_INSTALL_PREFIX=/usr
make %{?_smp_mflags}
```
and works build without asteroid-CMakeLists.txt.patch

Could you add to CMakeLists.txt

```
-lm ${OPENGL_LIBRARIES}
```

That I not must use in spec sed?

**Comment by chazomaticus** [comment]
Awesome, glad that works!

I'm not clear on why the `-lm...` bit is necessary.  If you look in [CMakeLists.txt now](https://github.com/chazomaticus/asteroid/blob/64869dfe745800f34f1c68248ba2e350dc95a592/CMakeLists.txt#L70), `m` is already included in the list of libraries.  Does it need to be `-lm` instead of just `m` on some systems?

**Comment by chazomaticus** [comment]
I'm closing this because I haven't heard from anybody about it in a while and I believe there's nothing left to be done.  If I'm wrong, please feel free to re-open!
